"""add foreign key to Review

Revision ID: 120da5d24dac
Revises: 8a2bb47bebd7
Create Date: 2024-10-02 23:14:35.624439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120da5d24dac'
down_revision = '8a2bb47bebd7'
branch_labels = None
depends_on = None




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
